name: CI

on:
  pull_request:
    branches: [main, master]
    paths-ignore: ['**.md', '**.txt', 'docs/**']

jobs:
  ci:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: swift test
